Updated code

diff --git a/jenkinsfile-s b/jenkinsfile-s
--- a/jenkinsfile-s
+++ b/jenkinsfile-s
@@ -1,11 +1,17 @@
 node('workstation') {
-
+  try{
     stage ("one"){
        echo "one"
+       exit 1
           }
 
 
     stage ("two"){
      echo "two"
-         }
+     }
+  } catch(e) {
+         stage('Declarative : post actions') {
+            echo 'this will be run if any failed'
+              }
+  }
 }
